### ISSUE TITLE
Resharper 9

### ISSUE THREAD

**Issue by davscro** [DanielTheCoder/ReSharper.Templates#6]
Can we upgrade it for R#9 support?
Thanks,
Davor

**Comment by DanielTheCoder** [comment]
Are there any changes in the new SDK or should it be enough to update version numbers in the package?

**Comment by davscro** [comment]
I think just updating version numbers should be enough.
Best,
Davor

**Comment by janv8000** [comment]
> This document lists the major changes between ReSharper 8 and ReSharper 9, for extension authors.
https://www.jetbrains.com/help/resharper/sdk/Extensions/WhatsNew.html
